# Generated by Django 5.2.17 on 2026-09-21 08:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0003_alter_department_department_type_and_more'),
        ('masterdata', '0001_initial'),
        ('wms', '0003_stockreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='设备编号')),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('agv', 'AGV 无人搬运车'), ('shuttle', '穿梭车'), ('stacker', '堆垛机'), ('robot', '工业机器人'), ('conveyor', '输送线'), ('other', '其他')], db_index=True, max_length=16, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('running', '作业中'), ('charging', '充电中'), ('fault', '故障'), ('maintenance', '保养维修'), ('offline', '离线')], db_index=True, default='idle', max_length=16, verbose_name='运行状态')),
                ('location', models.CharField(blank=True, default='', max_length=128, verbose_name='默认停靠点')),
                ('max_load', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='额定载重')),
                ('speed', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='米/分钟', max_digits=18, verbose_name='运行速度')),
                ('battery_level', models.PositiveSmallIntegerField(default=100, verbose_name='电量（%）')),
                ('commissioned_date', models.DateField(blank=True, null=True, verbose_name='投用日期')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次保养日期')),
                ('next_maintenance_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='下次保养日期')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.workshop', verbose_name='所在车间')),
            ],
            options={
                'verbose_name': '自动化设备',
                'verbose_name_plural': '自动化设备',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('task_no', models.CharField(max_length=32, verbose_name='任务编号')),
                ('task_type', models.CharField(choices=[('move', '搬运'), ('inbound', '上架入库'), ('outbound', '下架出库'), ('picking', '拣选配送'), ('transfer', '库内移库'), ('counting', '盘点搬运')], default='move', max_length=16, verbose_name='任务类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='normal', max_length=16, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待下发'), ('dispatched', '已下发'), ('executing', '执行中'), ('finished', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16, verbose_name='任务状态')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='数量')),
                ('container_no', models.CharField(blank=True, default='', max_length=64, verbose_name='容器/托盘号')),
                ('planned_at', models.DateTimeField(blank=True, null=True, verbose_name='计划执行时间')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='下发时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('result', models.TextField(blank=True, default='', verbose_name='执行结果')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='执行人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='logistics.automationdevice', verbose_name='执行设备')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wms.location', verbose_name='起点库位')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.material', verbose_name='物料')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='申请人')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wms.location', verbose_name='目标库位')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wms.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '物流任务',
                'verbose_name_plural': '物流任务',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('action', models.CharField(choices=[('create', '创建任务'), ('dispatch', '下发任务'), ('start', '开始执行'), ('finish', '完成执行'), ('cancel', '取消任务'), ('status_change', '设备状态变更')], db_index=True, max_length=16, verbose_name='操作类型')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='操作时间')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作说明')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='logistics.automationdevice', verbose_name='设备')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='操作人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='logistics.logisticstask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '物流操作日志',
                'verbose_name_plural': '物流操作日志',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='automationdevice',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_automation_device_company_code'),
        ),
        migrations.AddConstraint(
            model_name='automationdevice',
            constraint=models.CheckConstraint(condition=models.Q(('battery_level__lte', 100)), name='ck_automation_device_battery_range'),
        ),
        migrations.AddConstraint(
            model_name='automationdevice',
            constraint=models.CheckConstraint(condition=models.Q(('max_load__gte', 0)), name='ck_automation_device_load_non_negative'),
        ),
        migrations.AddIndex(
            model_name='logisticstask',
            index=models.Index(fields=['company', 'status'], name='idx_logistics_task_status'),
        ),
        migrations.AddConstraint(
            model_name='logisticstask',
            constraint=models.UniqueConstraint(fields=('company', 'task_no'), name='uq_logistics_task_company_no'),
        ),
        migrations.AddConstraint(
            model_name='logisticstask',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='ck_logistics_task_quantity'),
        ),
        migrations.AddIndex(
            model_name='logisticsoperationlog',
            index=models.Index(fields=['company', 'action'], name='idx_logistics_log_action'),
        ),
    ]
