# Generated by Django 5.2.17 on 2026-09-17 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='供应商编码')),
                ('name', models.CharField(max_length=128, verbose_name='供应商名称')),
                ('short_name', models.CharField(blank=True, default='', max_length=64, verbose_name='供应商简称')),
                ('category', models.CharField(choices=[('fabric', '面料'), ('accessory', '辅料'), ('packaging', '包装物'), ('equipment', '设备'), ('spare_part', '备品备件'), ('service', '服务'), ('other', '其他')], db_index=True, default='fabric', max_length=16, verbose_name='供应类别')),
                ('grade', models.CharField(choices=[('A', 'A 级（优先）'), ('B', 'B 级（合格）'), ('C', 'C 级（限用）'), ('D', 'D 级（观察）')], default='C', max_length=4, verbose_name='供应商等级')),
                ('admission_status', models.CharField(choices=[('pending', '待准入'), ('admitted', '已准入'), ('rejected', '未通过'), ('suspended', '暂停合作'), ('terminated', '已终止')], db_index=True, default='pending', max_length=16, verbose_name='准入状态')),
                ('payment_terms', models.CharField(blank=True, default='', max_length=64, verbose_name='结算方式')),
                ('tax_no', models.CharField(blank=True, default='', max_length=32, verbose_name='纳税人识别号')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址')),
                ('primary_contact_name', models.CharField(blank=True, default='', max_length=64, verbose_name='主要联系人')),
                ('primary_contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='主要联系电话')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='采购员')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('position', models.CharField(blank=True, default='', max_length=64, verbose_name='职务')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='电话')),
                ('email', models.CharField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='srm.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '供应商联系人',
                'verbose_name_plural': '供应商联系人',
                'ordering': ['supplier_id', '-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('qualification_type', models.CharField(choices=[('business_license', '营业执照'), ('quality_system', '质量体系认证'), ('environmental', '环保资质'), ('test_report', '检测报告'), ('social_compliance', '社会责任审核'), ('other', '其他')], db_index=True, max_length=32, verbose_name='资质类型')),
                ('certificate_no', models.CharField(blank=True, default='', max_length=64, verbose_name='证书编号')),
                ('issued_by', models.CharField(blank=True, default='', max_length=128, verbose_name='发证机构')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='到期日期')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('dedup_key', models.CharField(blank=True, editable=False, max_length=191, null=True, unique=True, verbose_name='去重键')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='srm.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '供应商资质',
                'verbose_name_plural': '供应商资质',
                'ordering': ['supplier_id', 'qualification_type', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_supplier_company_code'),
        ),
        migrations.AddConstraint(
            model_name='suppliercontact',
            constraint=models.UniqueConstraint(fields=('supplier', 'name'), name='uq_supplier_contact_name'),
        ),
        migrations.AddConstraint(
            model_name='supplierqualification',
            constraint=models.CheckConstraint(condition=models.Q(('issued_date__isnull', True), ('expiry_date__isnull', True), ('expiry_date__gte', models.F('issued_date')), _connector='OR'), name='ck_supplier_qualification_date_order'),
        ),
    ]
