# Generated by Django 5.2.17 on 2026-09-21 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ems', '0002_energyalarm_source_ref'),
        ('equipment', '0002_abnormaltype_abnormaltask_abnormalrecord_faultreport_and_more'),
        ('factory', '0003_alter_department_department_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='连接编码')),
                ('name', models.CharField(max_length=64, verbose_name='连接名称')),
                ('protocol', models.CharField(choices=[('http', 'HTTP 上报（已实现）'), ('simulator', '内置模拟器（模拟数据）'), ('mqtt', 'MQTT（待协议确认，未实现）'), ('modbus', 'Modbus（待协议确认，未实现）')], default='http', max_length=16, verbose_name='采集协议')),
                ('endpoint', models.CharField(blank=True, default='', help_text='如 http://10.0.0.8:8080/report', max_length=128, verbose_name='接入地址')),
                ('credential_ref', models.CharField(blank=True, default='', help_text='凭证**说明或引用位置**，平台不在此保存明文密码或密钥', max_length=128, verbose_name='凭证引用')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, verbose_name='超时（秒）')),
                ('batch_limit', models.PositiveIntegerField(default=200, help_text='超过上限的报文会被拒绝', verbose_name='单次上报测点上限')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='按网关统计；0 表示不限制', verbose_name='每分钟上报次数上限')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用采集')),
                ('is_simulated', models.BooleanField(default=False, help_text='模拟连接产生的数据会全程标注为「模拟」', verbose_name='模拟连接')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '数采连接配置',
                'verbose_name_plural': '数采连接配置',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IoTGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='设备编码')),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('gateway_type', models.CharField(choices=[('gateway', '采集网关'), ('sensor', '传感器'), ('electric_meter', '智能电表'), ('water_meter', '智能水表'), ('plc', 'PLC（只读采集）'), ('other', '其他')], default='gateway', max_length=16, verbose_name='设备类型')),
                ('location', models.CharField(blank=True, default='', max_length=128, verbose_name='安装位置')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('online', '在线'), ('offline', '离线'), ('disabled', '已停用')], db_index=True, default='unknown', max_length=16, verbose_name='在线状态')),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最近上报时间')),
                ('offline_minutes', models.PositiveIntegerField(default=0, help_text='超过该时长未上报即判定离线；0 表示不判定', verbose_name='离线判定（分钟）')),
                ('token_prefix', models.CharField(blank=True, default='', max_length=16, verbose_name='令牌前缀')),
                ('token_hash', models.CharField(blank=True, default='', help_text='设备令牌的 SHA-256 摘要', max_length=64, verbose_name='令牌摘要')),
                ('token_rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='令牌更新时间')),
                ('is_simulated', models.BooleanField(db_index=True, default=False, verbose_name='模拟设备')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateways', to='iot.iotconnection', verbose_name='连接配置')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iot_gateways', to='equipment.equipment', verbose_name='关联设备台账')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.factory', verbose_name='工厂')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.productionline', verbose_name='线体')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.workshop', verbose_name='车间')),
            ],
            options={
                'verbose_name': '数采设备',
                'verbose_name_plural': '数采设备',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IoTMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('message_id', models.CharField(max_length=64, verbose_name='消息 ID')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='接收时间')),
                ('device_time', models.DateTimeField(blank=True, null=True, verbose_name='设备时间')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='原始报文')),
                ('point_count', models.PositiveIntegerField(default=0, verbose_name='测点数')),
                ('status', models.CharField(choices=[('received', '已接收'), ('processed', '已处理'), ('duplicated', '重复报文'), ('failed', '处理失败')], db_index=True, default='received', max_length=16, verbose_name='处理状态')),
                ('error_message', models.CharField(blank=True, default='', max_length=255, verbose_name='处理说明')),
                ('is_simulated', models.BooleanField(db_index=True, default=False, verbose_name='模拟数据')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='iot.iotgateway', verbose_name='数采设备')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '采集报文',
                'verbose_name_plural': '采集报文',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IoTPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='测点编码')),
                ('name', models.CharField(max_length=64, verbose_name='测点名称')),
                ('quantity', models.CharField(choices=[('temperature', '温度'), ('voltage', '电压'), ('current', '电流'), ('vibration', '振动'), ('pressure', '压力'), ('flow', '流量'), ('electricity', '电量'), ('water', '水量'), ('gas', '气量'), ('other', '其他')], default='other', max_length=16, verbose_name='物理量')),
                ('unit', models.CharField(blank=True, default='', max_length=16, verbose_name='单位')),
                ('range_min', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='量程下限')),
                ('range_max', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='量程上限')),
                ('precision', models.PositiveSmallIntegerField(default=3, verbose_name='小数位')),
                ('is_cumulative', models.BooleanField(default=False, help_text='累计值（如电能表底）与瞬时值的统计口径不同', verbose_name='累计值')),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='上限')),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='下限')),
                ('alarm_enabled', models.BooleanField(default=True, verbose_name='越限报警')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='iot.iotgateway', verbose_name='数采设备')),
                ('meter', models.ForeignKey(blank=True, help_text='仅作对照线索：首版**不**把采集读数自动写入能源抄表，避免重复计量', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iot_points', to='ems.energymeter', verbose_name='关联计量仪表')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '采集测点',
                'verbose_name_plural': '采集测点',
                'ordering': ['gateway_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IoTReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('device_time', models.DateTimeField(db_index=True, verbose_name='设备时间')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='接收时间')),
                ('value', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='读数')),
                ('unit', models.CharField(blank=True, default='', max_length=16, verbose_name='单位')),
                ('quality', models.CharField(choices=[('good', '正常'), ('uncertain', '可疑'), ('bad', '异常')], default='good', max_length=16, verbose_name='数据质量')),
                ('source', models.CharField(choices=[('device', '设备上报'), ('simulator', '模拟器')], default='device', max_length=16, verbose_name='数据来源')),
                ('is_simulated', models.BooleanField(db_index=True, default=False, verbose_name='模拟数据')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.iotgateway', verbose_name='数采设备')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='iot.iotmessage', verbose_name='来源报文')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.iotpoint', verbose_name='测点')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '采集读数',
                'verbose_name_plural': '采集读数',
                'ordering': ['-device_time', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='iotconnection',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_iot_connection_company_code'),
        ),
        migrations.AddConstraint(
            model_name='iotconnection',
            constraint=models.CheckConstraint(condition=models.Q(('batch_limit__gt', 0)), name='ck_iot_connection_batch_limit_positive'),
        ),
        migrations.AddIndex(
            model_name='iotgateway',
            index=models.Index(fields=['company', 'status'], name='idx_iot_gateway_status'),
        ),
        migrations.AddConstraint(
            model_name='iotgateway',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_iot_gateway_company_code'),
        ),
        migrations.AddIndex(
            model_name='iotmessage',
            index=models.Index(fields=['gateway', 'message_id'], name='idx_iot_message_dedupe'),
        ),
        migrations.AddIndex(
            model_name='iotmessage',
            index=models.Index(fields=['company', 'status'], name='idx_iot_message_status'),
        ),
        migrations.AddIndex(
            model_name='iotpoint',
            index=models.Index(fields=['gateway', 'is_active'], name='idx_iot_point_active'),
        ),
        migrations.AddConstraint(
            model_name='iotpoint',
            constraint=models.UniqueConstraint(fields=('company', 'gateway', 'code'), name='uq_iot_point_gateway_code'),
        ),
        migrations.AddIndex(
            model_name='iotreading',
            index=models.Index(fields=['company', 'point', 'device_time'], name='idx_iot_reading_timeline'),
        ),
        migrations.AddIndex(
            model_name='iotreading',
            index=models.Index(fields=['company', 'received_at'], name='idx_iot_reading_received'),
        ),
        migrations.AddConstraint(
            model_name='iotreading',
            constraint=models.UniqueConstraint(fields=('point', 'device_time'), name='uq_iot_reading_point_time'),
        ),
    ]
