# Generated by Django 5.2.17 on 2026-09-17 03:39

import apps.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('file', models.FileField(max_length=255, upload_to=apps.core.models.attachment_upload_to, verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(blank=True, default='', max_length=128, verbose_name='内容类型')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='内容摘要')),
                ('biz_type', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='业务类型')),
                ('biz_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务主键')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='请求标识')),
                ('action', models.CharField(choices=[('login', '登录'), ('login_failed', '登录失败'), ('logout', '退出登录'), ('create', '新增'), ('update', '修改'), ('delete', '删除'), ('activate', '启用'), ('deactivate', '停用'), ('submit', '提交'), ('approve', '审批通过'), ('reject', '审批驳回'), ('withdraw', '撤回'), ('export', '导出'), ('upload', '上传'), ('download', '下载'), ('import', '导入')], db_index=True, max_length=32, verbose_name='操作类型')),
                ('actor_username', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人账号快照')),
                ('actor_name', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人姓名快照')),
                ('object_type', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='对象主键')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='对象描述')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='关键字段变更摘要')),
                ('reason', models.TextField(blank=True, default='', verbose_name='原因')),
                ('approval_basis', models.CharField(blank=True, default='', max_length=255, verbose_name='审批依据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='客户端')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='规则编码')),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('pattern', models.CharField(help_text='例：SO{YYYYMMDD}{SEQ:4}', max_length=128, verbose_name='编号格式')),
                ('reset_period', models.CharField(choices=[('never', '不重置'), ('daily', '每日'), ('monthly', '每月'), ('yearly', '每年')], default='never', max_length=16, verbose_name='重置周期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '编码规则',
                'verbose_name_plural': '编码规则',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_key', models.CharField(max_length=16, verbose_name='周期键')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='当前流水值')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '编码流水',
                'verbose_name_plural': '编码流水',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='字典编码')),
                ('name', models.CharField(max_length=128, verbose_name='字典名称')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=64, verbose_name='项编码')),
                ('label', models.CharField(max_length=128, verbose_name='项名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展属性')),
            ],
            options={
                'verbose_name': '字典明细',
                'verbose_name_plural': '字典明细',
                'ordering': ['dictionary_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=128, verbose_name='幂等范围')),
                ('key', models.CharField(max_length=128, verbose_name='幂等标识')),
                ('request_hash', models.CharField(max_length=64, verbose_name='请求内容摘要')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='响应内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '幂等记录',
                'verbose_name_plural': '幂等记录',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', verbose_name='内容')),
                ('biz_type', models.CharField(blank=True, default='', max_length=128, verbose_name='业务类型')),
                ('biz_id', models.CharField(blank=True, default='', max_length=64, verbose_name='业务主键')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='读取时间')),
                ('source_event_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='来源事件')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='事件标识')),
                ('event_type', models.CharField(db_index=True, max_length=128, verbose_name='事件类型')),
                ('aggregate_type', models.CharField(max_length=128, verbose_name='聚合类型')),
                ('aggregate_id', models.CharField(max_length=64, verbose_name='聚合主键')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成'), ('failed', '待重试'), ('dead', '需人工处理')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='已尝试次数')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='最大尝试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次重试时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('dedup_key', models.CharField(blank=True, max_length=191, null=True, unique=True, verbose_name='去重键')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
            ],
            options={
                'verbose_name': '发件箱事件',
                'verbose_name_plural': '发件箱事件',
                'ordering': ['id'],
            },
        ),
    ]
