# Generated by Django 5.2.17 on 2026-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', '登录'), ('login_failed', '登录失败'), ('logout', '退出登录'), ('create', '新增'), ('update', '修改'), ('delete', '删除'), ('activate', '启用'), ('deactivate', '停用'), ('submit', '提交'), ('approve', '审批通过'), ('reject', '审批驳回'), ('withdraw', '撤回'), ('export', '导出'), ('upload', '上传'), ('download', '下载'), ('import', '导入'), ('post', '过账'), ('reverse', '冲销')], db_index=True, max_length=32, verbose_name='操作类型'),
        ),
    ]
