# Generated by Django 5.2.17 on 2026-09-21 07:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0003_alter_department_department_type_and_more'),
        ('masterdata', '0001_initial'),
        ('srm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='类型编码')),
                ('name', models.CharField(max_length=64, verbose_name='类型名称')),
                ('category', models.CharField(choices=[('production', '生产设备'), ('utility', '公用工程设备'), ('inspection', '检测设备'), ('logistics', '物流设备'), ('auxiliary', '辅助设备'), ('other', '其他')], db_index=True, default='production', max_length=16, verbose_name='设备分类')),
                ('is_special', models.BooleanField(default=False, help_text='锅炉、压力容器、起重机械等需定期检验的设备', verbose_name='特种设备')),
                ('maintenance_cycle_days', models.PositiveIntegerField(default=0, help_text='0 表示尚未设定周期；保养计划增量启用后按此排期', verbose_name='保养周期（天）')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='设备编号')),
                ('name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('status', models.CharField(choices=[('in_use', '在用'), ('idle', '闲置'), ('repairing', '维修中'), ('stopped', '停用'), ('scrapped', '已报废')], db_index=True, default='in_use', max_length=16, verbose_name='设备状态')),
                ('location', models.CharField(blank=True, default='', max_length=128, verbose_name='安装位置')),
                ('brand', models.CharField(blank=True, default='', max_length=64, verbose_name='品牌')),
                ('model_no', models.CharField(blank=True, default='', max_length=64, verbose_name='规格型号')),
                ('serial_no', models.CharField(blank=True, default='', max_length=64, verbose_name='出厂编号')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='启用日期')),
                ('original_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='资产原值')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='保修截止日期')),
                ('is_special', models.BooleanField(default=False, verbose_name='特种设备')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.factory', verbose_name='所属工厂')),
                ('owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.department', verbose_name='负责部门')),
                ('owner_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='责任人')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.productionline', verbose_name='所属线体')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.station', verbose_name='工位')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='srm.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.workshop', verbose_name='所属车间')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.equipmenttype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备台账',
                'verbose_name_plural': '设备台账',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='备件编码')),
                ('name', models.CharField(max_length=128, verbose_name='备件名称')),
                ('part_type', models.CharField(choices=[('wear', '易损件'), ('standard', '标准件'), ('electric', '电气件'), ('mechanical', '机械件'), ('consumable', '耗材'), ('other', '其他')], db_index=True, default='wear', max_length=16, verbose_name='备件类别')),
                ('spec', models.CharField(blank=True, default='', max_length=64, verbose_name='规格型号')),
                ('safety_stock', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='安全库存')),
                ('reference_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='参考单价')),
                ('life_days', models.PositiveIntegerField(default=0, help_text='0 表示未设定寿命', verbose_name='参考寿命（天）')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_parts', to='equipment.equipmenttype', verbose_name='适用设备类型')),
                ('material', models.ForeignKey(blank=True, help_text='关联后该备件的库存与采购复用统一库存服务与采购模块', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.material', verbose_name='对应物料')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='srm.supplier', verbose_name='常用供应商')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.uom', verbose_name='单位')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '备品备件',
                'verbose_name_plural': '备品备件',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('name', models.CharField(max_length=64, verbose_name='零部件名称')),
                ('part_type', models.CharField(choices=[('wear', '易损件'), ('standard', '标准件'), ('electric', '电气件'), ('mechanical', '机械件'), ('consumable', '耗材'), ('other', '其他')], db_index=True, default='wear', max_length=16, verbose_name='零件类别')),
                ('spec', models.CharField(blank=True, default='', max_length=64, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=20, verbose_name='数量')),
                ('position', models.CharField(blank=True, default='', max_length=64, verbose_name='安装位置')),
                ('life_days', models.PositiveIntegerField(default=0, help_text='0 表示未设定寿命', verbose_name='参考寿命（天）')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='equipment.equipment', verbose_name='设备')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.uom', verbose_name='单位')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '设备零部件',
                'verbose_name_plural': '设备零部件',
                'ordering': ['equipment_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('equipment', 'name'), name='uq_equipment_part_name'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='ck_equipment_part_quantity_non_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipmenttype',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_equipment_type_code'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_equipment_company_code'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('original_value__gte', 0)), name='ck_equipment_original_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sparepart',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_spare_part_company_code'),
        ),
        migrations.AddConstraint(
            model_name='sparepart',
            constraint=models.CheckConstraint(condition=models.Q(('safety_stock__gte', 0)), name='ck_spare_part_safety_stock_non_negative'),
        ),
    ]
