# Generated by Django 5.2.17 on 2026-09-17 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=64, verbose_name='仓库名称')),
                ('warehouse_type', models.CharField(choices=[('raw', '原料仓'), ('wip', '半成品仓'), ('finished', '成品仓'), ('spare', '备件仓'), ('consumable', '耗材仓'), ('quarantine', '待检仓')], default='raw', max_length=16, verbose_name='仓库类型')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址')),
                ('manager_name', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='默认禁止负库存；即使开启也必须由库存服务显式判定并留痕。', verbose_name='允许负库存')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='factory.department', verbose_name='管理部门')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='factory.factory', verbose_name='所属工厂')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['company_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='库区编码')),
                ('name', models.CharField(max_length=64, verbose_name='库区名称')),
                ('zone_type', models.CharField(choices=[('receiving', '收货区'), ('storage', '存储区'), ('picking', '拣货区'), ('shipping', '发货区'), ('quarantine', '待检区'), ('return', '退货区')], default='storage', max_length=16, verbose_name='库区类型')),
                ('allow_mixed_batch', models.BooleanField(default=False, verbose_name='允许混批次')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='wms.warehouse')),
            ],
            options={
                'verbose_name': '库区',
                'verbose_name_plural': '库区',
                'ordering': ['warehouse_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='储位编码')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='储位名称')),
                ('location_type', models.CharField(choices=[('shelf', '货架储位'), ('floor', '地面储位'), ('rack', '托盘位'), ('staging', '暂存位')], default='shelf', max_length=16, verbose_name='储位类型')),
                ('row_no', models.CharField(blank=True, default='', max_length=16, verbose_name='排')),
                ('column_no', models.CharField(blank=True, default='', max_length=16, verbose_name='列')),
                ('level_no', models.CharField(blank=True, default='', max_length=16, verbose_name='层')),
                ('capacity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='容量')),
                ('is_locked', models.BooleanField(default=False, help_text='冻结储位不允许新的上架与移入操作。', verbose_name='冻结')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='wms.zone')),
            ],
            options={
                'verbose_name': '储位',
                'verbose_name_plural': '储位',
                'ordering': ['zone_id', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_warehouse_company_code'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='uq_zone_warehouse_code'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['zone', 'is_active'], name='idx_location_zone_active'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='uq_location_zone_code'),
        ),
    ]
