# Generated by Django 5.2.17 on 2026-09-17 06:11

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_initial'),
        ('masterdata', '0001_initial'),
        ('wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('document_no', models.CharField(blank=True, default='', max_length=32, verbose_name='单据编号')),
                ('document_type', models.CharField(choices=[('receipt', '收货入库'), ('issue', '出库'), ('move', '移库'), ('adjustment', '库存调整'), ('quality', '质量状态转换')], db_index=True, max_length=16, verbose_name='单据类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('posted', '已过账'), ('reversed', '已冲销'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('biz_type', models.CharField(blank=True, default='', max_length=32, verbose_name='来源单据类型')),
                ('biz_id', models.CharField(blank=True, default='', max_length=64, verbose_name='来源单据主键')),
                ('biz_no', models.CharField(blank=True, default='', max_length=64, verbose_name='来源单据编号')),
                ('idempotency_key', models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True, verbose_name='过账幂等键')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='过账时间')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='冲销时间')),
                ('reverse_reason', models.TextField(blank=True, default='', verbose_name='冲销原因')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='过账人')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='冲销人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='wms.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存单据',
                'verbose_name_plural': '库存单据',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='行号')),
                ('batch_no', models.CharField(blank=True, default='', max_length=64, verbose_name='批次号')),
                ('roll_no', models.CharField(blank=True, default='', max_length=64, verbose_name='卷号')),
                ('quality_status', models.CharField(choices=[('quarantine', '待检'), ('qualified', '合格'), ('rejected', '不合格')], default='quarantine', max_length=16, verbose_name='质量状态')),
                ('target_quality_status', models.CharField(blank=True, choices=[('quarantine', '待检'), ('qualified', '合格'), ('rejected', '不合格')], default='', max_length=16, verbose_name='目标质量状态')),
                ('direction', models.CharField(choices=[('in', '增加'), ('out', '减少')], default='in', help_text='仅库存调整单使用：增加=盘盈、减少=盘亏。', max_length=8, verbose_name='调整方向')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='数量')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.inventorydocument', verbose_name='单据')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wms.location', verbose_name='储位')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.material', verbose_name='物料')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wms.location', verbose_name='目标储位')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '库存单据行',
                'verbose_name_plural': '库存单据行',
                'ordering': ['document_id', 'line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('receipt', '入库'), ('issue', '出库'), ('move_out', '移库转出'), ('move_in', '移库转入'), ('adjust_up', '盘盈调整'), ('adjust_down', '盘亏调整'), ('quality_out', '质量转换转出'), ('quality_in', '质量转换转入')], db_index=True, max_length=16, verbose_name='流水类型')),
                ('batch_no', models.CharField(blank=True, default='', max_length=64, verbose_name='批次号')),
                ('roll_no', models.CharField(blank=True, default='', max_length=64, verbose_name='卷号')),
                ('quality_status', models.CharField(choices=[('quarantine', '待检'), ('qualified', '合格'), ('rejected', '不合格')], db_index=True, max_length=16, verbose_name='质量状态')),
                ('dimension_key', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='维度键')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='数量')),
                ('on_hand_before', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='过账前实存量')),
                ('on_hand_after', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='过账后实存量')),
                ('frozen_after', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='过账后冻结量')),
                ('reserved_after', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='过账后占用量')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='原因')),
                ('dedup_key', models.CharField(blank=True, editable=False, max_length=191, null=True, unique=True, verbose_name='去重键')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发生时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='factory.company', verbose_name='所属公司')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wms.inventorydocument', verbose_name='库存单据')),
                ('document_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wms.inventorydocumentline', verbose_name='单据行')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='wms.location', verbose_name='储位')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='masterdata.material', verbose_name='物料')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='wms.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('batch_no', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='批次号')),
                ('roll_no', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='卷号')),
                ('quality_status', models.CharField(choices=[('quarantine', '待检'), ('qualified', '合格'), ('rejected', '不合格')], db_index=True, default='quarantine', max_length=16, verbose_name='质量状态')),
                ('dimension_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='维度键')),
                ('on_hand', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='实存量')),
                ('frozen', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='冻结量')),
                ('reserved', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='占用量')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='wms.location', verbose_name='储位')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='masterdata.material', verbose_name='物料')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='wms.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存余额',
                'verbose_name_plural': '库存余额',
                'ordering': ['company_id', 'material_id', 'warehouse_id', 'id'],
                'indexes': [models.Index(fields=['material', 'warehouse', 'quality_status'], name='idx_balance_material_wh_qs'), models.Index(fields=['warehouse', 'location'], name='idx_balance_wh_location')],
                'constraints': [models.CheckConstraint(condition=models.Q(('on_hand__gte', 0), ('frozen__gte', 0), ('reserved__gte', 0)), name='ck_inventory_balance_non_negative'), models.CheckConstraint(condition=models.Q(('frozen__lte', django.db.models.expressions.CombinedExpression(models.F('on_hand'), '-', models.F('reserved')))), name='ck_inventory_balance_buckets_within_on_hand')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorydocument',
            constraint=models.UniqueConstraint(fields=('company', 'document_no'), name='uq_inventory_document_company_no'),
        ),
        migrations.AddConstraint(
            model_name='inventorydocumentline',
            constraint=models.UniqueConstraint(fields=('document', 'line_no'), name='uq_inventory_line_document_no'),
        ),
        migrations.AddConstraint(
            model_name='inventorydocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_inventory_line_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['material', 'warehouse', '-id'], name='idx_txn_material_wh_id'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['document', 'id'], name='idx_txn_document_id'),
        ),
    ]
