# Generated by Django 5.2.17 on 2026-09-17 08:52

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_initial'),
        ('masterdata', '0001_initial'),
        ('wms', '0002_inventorydocument_inventorydocumentline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('batch_no', models.CharField(blank=True, default='', max_length=64, verbose_name='批次号')),
                ('roll_no', models.CharField(blank=True, default='', max_length=64, verbose_name='卷号')),
                ('quality_status', models.CharField(choices=[('quarantine', '待检'), ('qualified', '合格'), ('rejected', '不合格')], db_index=True, default='qualified', max_length=16, verbose_name='质量状态')),
                ('dimension_key', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='维度键')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='占用数量')),
                ('consumed_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='已消耗数量')),
                ('released_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='已释放数量')),
                ('status', models.CharField(choices=[('active', '占用中'), ('closed', '已结束'), ('cancelled', '已取消')], db_index=True, default='active', max_length=16, verbose_name='状态')),
                ('biz_type', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='来源单据类型')),
                ('biz_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='来源单据主键')),
                ('biz_no', models.CharField(blank=True, default='', max_length=64, verbose_name='来源单据编号')),
                ('request_key', models.CharField(blank=True, editable=False, max_length=191, null=True, unique=True, verbose_name='占用幂等键')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wms.location', verbose_name='储位')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='masterdata.material', verbose_name='物料')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='wms.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存占用',
                'verbose_name_plural': '库存占用',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['dimension_key', 'status'], name='idx_reservation_dimension'), models.Index(fields=['biz_type', 'biz_id'], name='idx_reservation_biz')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_reservation_quantity_positive'), models.CheckConstraint(condition=models.Q(('consumed_quantity__gte', 0), ('released_quantity__gte', 0)), name='ck_reservation_consumed_non_negative'), models.CheckConstraint(condition=models.Q(('consumed_quantity__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '-', models.F('released_quantity')))), name='ck_reservation_within_quantity')],
            },
        ),
    ]
