# Generated by Django 5.2.17 on 2026-09-17 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('template_version', models.PositiveIntegerField(default=1, verbose_name='模板版本快照')),
                ('template_snapshot', models.JSONField(blank=True, default=dict, verbose_name='模板快照')),
                ('biz_type', models.CharField(db_index=True, max_length=64, verbose_name='业务类型')),
                ('biz_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务主键')),
                ('biz_no', models.CharField(blank=True, default='', max_length=64, verbose_name='业务单号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='申请说明')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='涉及金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('current_seq', models.PositiveIntegerField(default=0, verbose_name='当前节点顺序')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_instances', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_instances', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_instances', to='factory.department', verbose_name='申请部门')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '审批实例',
                'verbose_name_plural': '审批实例',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(verbose_name='顺序号')),
                ('name', models.CharField(max_length=64, verbose_name='节点名称')),
                ('approver_type', models.CharField(choices=[('role', '按角色'), ('user', '指定人员')], default='role', max_length=8, verbose_name='审批人类型')),
                ('status', models.CharField(choices=[('waiting', '未开始'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('skipped', '已跳过'), ('cancelled', '已取消')], db_index=True, default='waiting', max_length=16, verbose_name='状态')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('decision', models.CharField(blank=True, default='', max_length=16, verbose_name='处理结果')),
                ('comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.role')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.approvalinstance')),
            ],
            options={
                'verbose_name': '审批步骤',
                'verbose_name_plural': '审批步骤',
                'ordering': ['instance_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='节点顺序')),
                ('action', models.CharField(choices=[('submit', '提交'), ('approve', '通过'), ('reject', '驳回'), ('withdraw', '撤回'), ('comment', '意见')], max_length=16, verbose_name='动作')),
                ('actor_name', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人快照')),
                ('comment', models.TextField(blank=True, default='', verbose_name='意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.approvalinstance')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='workflow.approvalstep')),
            ],
            options={
                'verbose_name': '审批轨迹',
                'verbose_name_plural': '审批轨迹',
                'ordering': ['instance_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=128, verbose_name='模板名称')),
                ('biz_type', models.CharField(db_index=True, help_text='例如 generic.request、procurement.request；用于按业务选择模板。', max_length=64, verbose_name='业务类型')),
                ('allow_self_approval', models.BooleanField(default=False, help_text='默认关闭；开启属于例外授权，必须在审批轨迹中留痕。', verbose_name='允许申请人审批自己的单据')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='模板版本')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_templates', to='factory.company', verbose_name='适用公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '审批模板',
                'verbose_name_plural': '审批模板',
                'ordering': ['biz_type', 'code'],
            },
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.approvaltemplate'),
        ),
        migrations.CreateModel(
            name='ApprovalTemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('seq', models.PositiveIntegerField(verbose_name='顺序号')),
                ('name', models.CharField(max_length=64, verbose_name='节点名称')),
                ('approver_type', models.CharField(choices=[('role', '按角色'), ('user', '指定人员')], default='role', max_length=8, verbose_name='审批人类型')),
                ('amount_min', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='金额下限')),
                ('amount_max', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='金额上限')),
                ('department_ids', models.JSONField(blank=True, default=list, help_text='为空表示不限部门；否则申请人部门需命中列表。', verbose_name='适用部门')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_nodes', to='identity.role', verbose_name='审批角色')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='指定审批人')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.approvaltemplate')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'ordering': ['template_id', 'seq'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('instance', 'seq'), name='uq_approval_step_seq'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['status', '-id'], name='idx_approval_status'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['biz_type', 'biz_id'], name='idx_approval_biz'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['applicant', 'status'], name='idx_approval_applicant'),
        ),
        migrations.AddConstraint(
            model_name='approvaltemplatenode',
            constraint=models.UniqueConstraint(fields=('template', 'seq'), name='uq_template_node_seq'),
        ),
    ]
