# Generated by Django 5.2.17 on 2026-09-17 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('source_type', models.CharField(db_index=True, max_length=128, verbose_name='来源单据类型')),
                ('source_id', models.CharField(db_index=True, max_length=64, verbose_name='来源单据主键')),
                ('source_no', models.CharField(blank=True, default='', max_length=64, verbose_name='来源单据号')),
                ('target_type', models.CharField(db_index=True, max_length=128, verbose_name='目标单据类型')),
                ('target_id', models.CharField(db_index=True, max_length=64, verbose_name='目标单据主键')),
                ('target_no', models.CharField(blank=True, default='', max_length=64, verbose_name='目标单据号')),
                ('relation', models.CharField(choices=[('generated_from', '由...生成'), ('fulfills', '满足'), ('consumes', '消耗'), ('references', '关联'), ('reverses', '冲销')], default='generated_from', max_length=32, verbose_name='关系')),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='关联数量')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '单据关系',
                'verbose_name_plural': '单据关系',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='idx_doclink_target')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'target_type', 'target_id', 'relation'), name='uq_document_link')],
            },
        ),
    ]
