# Generated by Django 5.2.17 on 2026-09-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='公司编码')),
                ('name', models.CharField(max_length=128, verbose_name='公司名称')),
                ('short_name', models.CharField(blank=True, default='', max_length=64, verbose_name='简称')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, default='', max_length=64, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='部门编码')),
                ('name', models.CharField(max_length=128, verbose_name='部门名称')),
                ('department_type', models.CharField(choices=[('management', '职能部门'), ('production', '生产部门'), ('quality', '质量部门'), ('warehouse', '仓储部门'), ('other', '其他')], default='management', max_length=32, verbose_name='部门类型')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['company_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('employee_no', models.CharField(max_length=32, verbose_name='工号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=8, verbose_name='性别')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('position', models.CharField(blank=True, default='', max_length=64, verbose_name='岗位')),
                ('employment_type', models.CharField(choices=[('full_time', '正式'), ('temporary', '临时'), ('intern', '实习'), ('outsourced', '外包')], default='full_time', max_length=16, verbose_name='用工性质')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('status', models.CharField(choices=[('active', '在职'), ('leave', '休假'), ('resigned', '离职')], db_index=True, default='active', max_length=16, verbose_name='在职状态')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['company_id', 'employee_no'],
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='工厂编码')),
                ('name', models.CharField(max_length=128, verbose_name='工厂名称')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '工厂',
                'verbose_name_plural': '工厂',
                'ordering': ['company_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='线体编码')),
                ('name', models.CharField(max_length=128, verbose_name='线体名称')),
                ('line_type', models.CharField(choices=[('manual', '人工线'), ('hanging', '吊挂线'), ('automated', '自动化线')], default='manual', max_length=32, verbose_name='线体类型')),
                ('daily_capacity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='日产能')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '线体',
                'verbose_name_plural': '线体',
                'ordering': ['workshop_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='班次编码')),
                ('name', models.CharField(max_length=64, verbose_name='班次名称')),
                ('start_time', models.TimeField(verbose_name='上班时间')),
                ('end_time', models.TimeField(verbose_name='下班时间')),
                ('cross_day', models.BooleanField(default=False, verbose_name='跨夜班')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='休息时长(分钟)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '班次',
                'verbose_name_plural': '班次',
                'ordering': ['company_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='工位编码')),
                ('name', models.CharField(max_length=128, verbose_name='工位名称')),
                ('process_name', models.CharField(blank=True, default='', max_length=64, verbose_name='对应工序')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '工位',
                'verbose_name_plural': '工位',
                'ordering': ['line_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='班组编码')),
                ('name', models.CharField(max_length=64, verbose_name='班组名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('role_in_team', models.CharField(blank=True, default='', max_length=32, verbose_name='班组角色')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='加入日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='退出日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '班组成员',
                'verbose_name_plural': '班组成员',
                'ordering': ['team_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='车间编码')),
                ('name', models.CharField(max_length=128, verbose_name='车间名称')),
                ('workshop_type', models.CharField(choices=[('cutting', '裁剪'), ('sewing', '缝制'), ('ironing', '整烫'), ('inspection', '检验'), ('packing', '包装'), ('other', '其他')], default='sewing', max_length=32, verbose_name='车间类型')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '车间',
                'verbose_name_plural': '车间',
                'ordering': ['factory_id', 'sort_order', 'id'],
            },
        ),
    ]
