# Generated by Django 5.2.17 on 2026-09-18 07:00

from django.db import migrations, models


# 修正历史演示/早期数据里写错的枚举键。
# 背景：seed_demo 早期版本直接写了中文性别、以及不在 choices 里的类型值，
# 导致界面既可能显示英文、也可能显示不在枚举内的值。这里按「部门编码」精确映射，
# 其余无法判断的一律落到 other，不做静默丢弃。
DEPT_FIX = {
    "PUR": "procurement",
    "SALES": "sales",
    "WH": "warehouse",
    "EAM": "equipment",
}
VALID_DEPT_TYPES = {
    "management", "production", "quality", "warehouse",
    "procurement", "sales", "equipment", "other",
}
GENDER_FIX = {"男": "male", "女": "female"}
VALID_GENDERS = {"male", "female", "unknown"}
VALID_EMPLOYMENT_TYPES = {"full_time", "temporary", "intern", "outsourced"}
VALID_LINE_TYPES = {"manual", "hanging", "automated"}


def fix_enum_values(apps, schema_editor):
    Department = apps.get_model("factory", "Department")
    Employee = apps.get_model("factory", "Employee")
    ProductionLine = apps.get_model("factory", "ProductionLine")

    for dept in Department.objects.all():
        if dept.department_type in VALID_DEPT_TYPES:
            continue
        dept.department_type = DEPT_FIX.get(dept.code, "other")
        dept.save(update_fields=["department_type"])

    for employee in Employee.objects.all():
        changed = []
        if employee.gender not in VALID_GENDERS:
            employee.gender = GENDER_FIX.get(employee.gender, "unknown")
            changed.append("gender")
        if employee.employment_type not in VALID_EMPLOYMENT_TYPES:
            employee.employment_type = "full_time"
            changed.append("employment_type")
        if changed:
            employee.save(update_fields=changed)

    for line in ProductionLine.objects.all():
        if line.line_type in VALID_LINE_TYPES:
            continue
        line.line_type = "manual"
        line.save(update_fields=["line_type"])


def noop(apps, schema_editor):
    """不可逆的数据修正：向下迁移时保留现值，不做反向猜测。"""


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(fix_enum_values, noop),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('management', '职能部门'), ('production', '生产部门'), ('quality', '质量部门'), ('warehouse', '仓储部门'), ('procurement', '采购部门'), ('sales', '销售部门'), ('equipment', '设备部门'), ('other', '其他')], default='management', max_length=32, verbose_name='部门类型'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_type',
            field=models.CharField(choices=[('cutting', '裁剪'), ('sewing', '缝制'), ('ironing', '整烫'), ('finishing', '整烫包装'), ('inspection', '检验'), ('packing', '包装'), ('other', '其他')], default='sewing', max_length=32, verbose_name='车间类型'),
        ),
    ]
