# Generated by Django 5.2.17 on 2026-09-17 04:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='客户编码')),
                ('name', models.CharField(max_length=128, verbose_name='客户名称')),
                ('short_name', models.CharField(blank=True, default='', max_length=64, verbose_name='客户简称')),
                ('category', models.CharField(choices=[('brand', '品牌客户'), ('distributor', '经销商'), ('agent', '代理商'), ('direct', '直客'), ('online', '电商')], default='direct', max_length=16, verbose_name='客户分类')),
                ('level', models.CharField(choices=[('A', 'A 类（战略）'), ('B', 'B 类（重点）'), ('C', 'C 类（一般）'), ('D', 'D 类（观察）')], default='C', max_length=8, verbose_name='客户等级')),
                ('status', models.CharField(choices=[('potential', '潜在'), ('active', '合作中'), ('suspended', '暂停合作'), ('terminated', '已终止')], db_index=True, default='potential', max_length=16, verbose_name='合作状态')),
                ('credit_limit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='信用额度')),
                ('payment_terms', models.CharField(blank=True, default='', max_length=64, verbose_name='结算方式')),
                ('tax_no', models.CharField(blank=True, default='', max_length=32, verbose_name='纳税人识别号')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址')),
                ('primary_contact_name', models.CharField(blank=True, default='', max_length=64, verbose_name='主要联系人')),
                ('primary_contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='主要联系电话')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='业务员')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('position', models.CharField(blank=True, default='', max_length=64, verbose_name='职务')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='电话')),
                ('email', models.CharField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer', verbose_name='客户')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '客户联系人',
                'verbose_name_plural': '客户联系人',
                'ordering': ['customer_id', '-is_primary', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_customer_company_code'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0)), name='ck_customer_credit_limit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='uq_customer_contact_name'),
        ),
    ]
