# Generated by Django 5.2.17 on 2026-09-21 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('factory', '0003_alter_department_department_type_and_more'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('complaint_no', models.CharField(max_length=32, verbose_name='投诉编号')),
                ('complaint_type', models.CharField(choices=[('quality', '产品质量'), ('delivery', '交期延误'), ('service', '服务态度'), ('price', '价格与结算'), ('packaging', '包装与标识'), ('other', '其他')], db_index=True, default='quality', max_length=16, verbose_name='投诉类型')),
                ('level', models.CharField(choices=[('general', '一般'), ('important', '重要'), ('severe', '严重')], default='general', max_length=16, verbose_name='投诉级别')),
                ('status', models.CharField(choices=[('pending', '待受理'), ('handling', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], db_index=True, default='pending', max_length=16, verbose_name='处理状态')),
                ('source', models.CharField(choices=[('phone', '电话'), ('email', '邮件'), ('visit', '来访'), ('online', '线上（微信/电商）'), ('salesman', '业务员反馈'), ('other', '其他')], default='phone', max_length=16, verbose_name='投诉来源')),
                ('title', models.CharField(max_length=128, verbose_name='投诉主题')),
                ('content', models.TextField(verbose_name='投诉内容')),
                ('complained_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='投诉时间')),
                ('reporter', models.CharField(blank=True, default='', max_length=64, verbose_name='投诉人')),
                ('reporter_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='投诉人电话')),
                ('related_no', models.CharField(blank=True, default='', help_text='如销售订单号、发货单号；仅作追溯线索，不建立强外键', max_length=64, verbose_name='关联单据号')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='受理时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('handle_measure', models.TextField(blank=True, default='', verbose_name='处理措施')),
                ('satisfaction', models.PositiveSmallIntegerField(default=0, help_text='0 表示客户尚未评价；1~5 为回访评分', verbose_name='满意度评分')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='crm.customer', verbose_name='客户')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='处理人')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='受理人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '客户投诉',
                'verbose_name_plural': '客户投诉',
                'ordering': ['-complained_at', '-id'],
                'indexes': [models.Index(fields=['company', 'status'], name='idx_complaint_status')],
                'constraints': [models.UniqueConstraint(fields=('company', 'complaint_no'), name='uq_customer_complaint_company_no'), models.CheckConstraint(condition=models.Q(('satisfaction__gte', 0), ('satisfaction__lte', 5)), name='ck_customer_complaint_satisfaction_range')],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('review_no', models.CharField(max_length=32, verbose_name='评价编号')),
                ('product_desc', models.CharField(blank=True, default='', max_length=128, verbose_name='产品/款式描述')),
                ('score', models.PositiveSmallIntegerField(help_text='1~5 分，由客户给出', verbose_name='评分')),
                ('status', models.CharField(choices=[('pending', '待回复'), ('replied', '已回复'), ('closed', '已关闭')], db_index=True, default='pending', max_length=16, verbose_name='处理状态')),
                ('reviewer_name', models.CharField(blank=True, default='', max_length=64, verbose_name='评价人')),
                ('reviewed_at', models.DateField(db_index=True, verbose_name='评价日期')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('reply', models.TextField(blank=True, default='', verbose_name='回复内容')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_reviews', to='crm.customer', verbose_name='客户')),
                ('replier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='回复人')),
                ('sku', models.ForeignKey(blank=True, help_text='可选：评价到具体 SKU 时填写，否则只记录产品描述', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.sku', verbose_name='关联 SKU')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '产品评价',
                'verbose_name_plural': '产品评价',
                'ordering': ['-reviewed_at', '-id'],
                'indexes': [models.Index(fields=['company', 'status'], name='idx_product_review_status')],
                'constraints': [models.UniqueConstraint(fields=('company', 'review_no'), name='uq_product_review_company_no'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='ck_product_review_score_range')],
            },
        ),
    ]
