# Generated by Django 5.2.17 on 2026-09-18 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0002_initial'),
        ('masterdata', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=64, verbose_name='BOM 编号')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('scope_key', models.CharField(db_index=True, editable=False, max_length=96, verbose_name='范围键')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '审核中'), ('approved', '已审核'), ('rejected', '已驳回'), ('obsolete', '已作废')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('approval_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.approvalinstance', verbose_name='审批实例')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('sku', models.ForeignKey(blank=True, help_text='为空表示款式通用 BOM；填写表示该 SKU 的差异用料版本。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='masterdata.sku', verbose_name='差异 SKU')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='masterdata.style', verbose_name='款式')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '物料清单',
                'verbose_name_plural': '物料清单',
                'ordering': ['company_id', 'style_id', 'version_no'],
            },
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('line_no', models.PositiveIntegerField(verbose_name='行号')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='标准用量')),
                ('loss_rate', models.DecimalField(decimal_places=10, default=0, help_text='0.05 表示 5%', max_digits=18, verbose_name='损耗率')),
                ('line_type', models.CharField(choices=[('normal', '正常用料'), ('substitute', '替代料')], default='normal', max_length=16, verbose_name='行类型')),
                ('position', models.CharField(blank=True, default='', max_length=64, verbose_name='使用部位')),
                ('is_key_material', models.BooleanField(default=False, verbose_name='关键用料')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.bom')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.material', verbose_name='用料')),
                ('substitute_for', models.ForeignKey(blank=True, help_text='仅替代料行使用；必须指向同一 BOM 内的正常用料行。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitutes', to='planning.bomline', verbose_name='替代的用料行')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.uom', verbose_name='单位')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'BOM 明细',
                'verbose_name_plural': 'BOM 明细',
                'ordering': ['bom_id', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=64, verbose_name='工艺编号')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('scope_key', models.CharField(db_index=True, editable=False, max_length=96, verbose_name='范围键')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '审核中'), ('approved', '已审核'), ('rejected', '已驳回'), ('obsolete', '已作废')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('approval_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.approvalinstance', verbose_name='审批实例')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routings', to='masterdata.sku', verbose_name='差异 SKU')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routings', to='masterdata.style', verbose_name='款式')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '工艺路线',
                'verbose_name_plural': '工艺路线',
                'ordering': ['company_id', 'style_id', 'version_no'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('sequence', models.PositiveIntegerField(verbose_name='工序顺序')),
                ('name', models.CharField(max_length=64, verbose_name='工序名称')),
                ('workcenter', models.CharField(blank=True, default='', max_length=64, verbose_name='工作中心/线体')),
                ('equipment_requirement', models.CharField(blank=True, default='', max_length=128, verbose_name='设备要求')),
                ('standard_hours', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='标准工时（小时）')),
                ('is_quality_gate', models.BooleanField(default=False, verbose_name='工序质检点')),
                ('is_outsourced', models.BooleanField(default=False, verbose_name='外协工序')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='planning.routing')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.workshop', verbose_name='车间')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
                'ordering': ['routing_id', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_bom_company_code'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('company', 'scope_key', 'version_no'), name='uq_bom_scope_version'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='ck_bom_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_bom_effective_range'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.UniqueConstraint(fields=('bom', 'line_no'), name='uq_bom_line_no'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_bom_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('loss_rate__gte', 0)), name='ck_bom_line_loss_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('loss_rate__lt', 1)), name='ck_bom_line_loss_lt_one'),
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_routing_company_code'),
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.UniqueConstraint(fields=('company', 'scope_key', 'version_no'), name='uq_routing_scope_version'),
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='ck_routing_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='routingstep',
            constraint=models.UniqueConstraint(fields=('routing', 'sequence'), name='uq_routing_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='routingstep',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='ck_routing_step_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='routingstep',
            constraint=models.CheckConstraint(condition=models.Q(('standard_hours__gte', 0)), name='ck_routing_step_hours_non_negative'),
        ),
    ]
