# Generated by Django 5.2.17 on 2026-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyalarm',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text='报警的精确来源，如数采测点 iot:网关编码:测点编码；用于按来源去重与追溯', max_length=128, verbose_name='来源标识'),
        ),
    ]
