# Generated by Django 5.2.17 on 2026-09-17 03:39

import apps.identity.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='登录账号')),
                ('display_name', models.CharField(blank=True, default='', max_length=64, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='可登录后台')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='需强制修改密码')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='密码最后修改时间')),
                ('failed_login_count', models.PositiveIntegerField(default=0, verbose_name='连续登录失败次数')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定至')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最近登录 IP')),
                ('permission_version', models.PositiveIntegerField(default=0, verbose_name='权限版本')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='版本号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='factory.department', verbose_name='所属部门')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['username'],
            },
            managers=[
                ('objects', apps.identity.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='菜单编码')),
                ('name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('path', models.CharField(blank=True, default='', max_length=128, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, default='', max_length=128, verbose_name='前端组件')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='图标')),
                ('menu_type', models.CharField(choices=[('directory', '目录'), ('page', '页面'), ('button', '按钮')], default='page', max_length=16, verbose_name='菜单类型')),
                ('permission_code', models.CharField(blank=True, default='', max_length=128, verbose_name='进入所需权限编码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('visible', models.BooleanField(default=True, verbose_name='显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='identity.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=128, verbose_name='权限名称')),
                ('module', models.CharField(db_index=True, max_length=64, verbose_name='模块')),
                ('resource', models.CharField(max_length=64, verbose_name='资源')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('permission_type', models.CharField(choices=[('menu', '菜单权限'), ('action', '操作权限'), ('api', '接口权限'), ('data', '数据范围权限')], default='action', max_length=16, verbose_name='权限类型')),
                ('is_system', models.BooleanField(default=True, verbose_name='系统内置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '权限点',
                'verbose_name_plural': '权限点',
                'ordering': ['module', 'resource', 'action'],
                'indexes': [models.Index(fields=['module', 'resource'], name='idx_permission_module_resource')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='角色编码')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('data_scope_type', models.CharField(choices=[('all', '全部数据'), ('company', '本公司'), ('custom', '自定义组织范围'), ('factory', '指定工厂'), ('department', '指定部门'), ('warehouse', '指定仓库'), ('self', '仅本人')], default='self', max_length=16, verbose_name='数据范围')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='factory.company', verbose_name='归属公司')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='identity.menu')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='identity.permission')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='roles', through='identity.UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='登录账号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('successful', models.BooleanField(default=False, verbose_name='是否成功')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=128, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '登录记录',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='idx_login_attempt_user')],
            },
        ),
        migrations.CreateModel(
            name='RoleScopeGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('company', '公司'), ('factory', '工厂'), ('department', '部门'), ('warehouse', '仓库')], max_length=16, verbose_name='范围维度')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='对象主键')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_grants', to='identity.role')),
            ],
            options={
                'verbose_name': '角色数据范围',
                'verbose_name_plural': '角色数据范围',
                'constraints': [models.UniqueConstraint(fields=('role', 'dimension', 'object_id'), name='uq_role_scope_grant')],
            },
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uq_user_role'),
        ),
    ]
