# Generated by Django 5.2.17 on 2026-09-21 23:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_abnormaltype_abnormaltask_abnormalrecord_faultreport_and_more'),
        ('factory', '0003_alter_department_department_type_and_more'),
        ('masterdata', '0001_initial'),
        ('srm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('code', models.CharField(max_length=32, verbose_name='项目编码')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('category', models.CharField(choices=[('appearance', '外观'), ('size', '尺寸'), ('physical', '理化性能'), ('function', '功能'), ('package', '包装'), ('other', '其他')], db_index=True, default='appearance', max_length=16, verbose_name='项目类别')),
                ('value_type', models.CharField(choices=[('quantitative', '定量（按上下限自动判定）'), ('qualitative', '定性（目视 / 描述判定）')], default='quantitative', max_length=16, verbose_name='判定方式')),
                ('unit', models.CharField(blank=True, default='', max_length=16, verbose_name='单位')),
                ('method', models.CharField(blank=True, default='', max_length=255, verbose_name='检验方法与工具')),
                ('standard_text', models.CharField(blank=True, default='', max_length=255, verbose_name='标准要求')),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='标准下限')),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='标准上限')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '检验项目',
                'verbose_name_plural': '检验项目',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('order_no', models.CharField(max_length=32, verbose_name='检验单号')),
                ('inspection_type', models.CharField(choices=[('iqc', '来料检验'), ('ipqc', '过程检验'), ('fqc', '成品检验'), ('oqc', '出货检验'), ('first_article', '首件检验'), ('other', '其他')], db_index=True, default='iqc', max_length=16, verbose_name='检验类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('judged', '已判定'), ('closed', '已关闭')], db_index=True, default='draft', max_length=16, verbose_name='单据状态')),
                ('judgement', models.CharField(choices=[('pending', '待判定'), ('passed', '合格'), ('failed', '不合格'), ('concession', '让步接收')], db_index=True, default='pending', max_length=16, verbose_name='判定结论')),
                ('source_no', models.CharField(blank=True, default='', help_text='如采购收货单号、生产工单号', max_length=64, verbose_name='来源单据号')),
                ('product_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='产品 / 物料描述')),
                ('batch_no', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='批次号')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='受检数量')),
                ('sample_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='抽样数量')),
                ('unit', models.CharField(blank=True, default='', max_length=16, verbose_name='单位')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='检验时间')),
                ('judge_remark', models.TextField(blank=True, default='', verbose_name='判定说明')),
                ('judged_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='判定时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='equipment.equipment', verbose_name='受检设备')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='检验员')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.material', verbose_name='受检物料')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.productionline', verbose_name='受检线体')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='srm.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.workshop', verbose_name='受检车间')),
            ],
            options={
                'verbose_name': '检验单',
                'verbose_name_plural': '检验单',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('alert_no', models.CharField(max_length=32, verbose_name='报警编号')),
                ('level', models.CharField(choices=[('minor', '轻微'), ('major', '严重'), ('critical', '致命')], db_index=True, default='major', max_length=16, verbose_name='报警级别')),
                ('status', models.CharField(choices=[('open', '待处理'), ('handling', '处理中'), ('closed', '已关闭')], db_index=True, default='open', max_length=16, verbose_name='处理状态')),
                ('title', models.CharField(max_length=255, verbose_name='报警主题')),
                ('description', models.TextField(blank=True, default='', verbose_name='报警说明')),
                ('batch_no', models.CharField(blank=True, default='', max_length=64, verbose_name='批次号')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('close_remark', models.TextField(blank=True, default='', verbose_name='关闭说明')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.employee', verbose_name='处理人')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.material', verbose_name='物料')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='qms.qualityinspectionorder', verbose_name='来源检验单')),
            ],
            options={
                'verbose_name': '质量报警',
                'verbose_name_plural': '质量报警',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('measured_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='实测值')),
                ('text_value', models.CharField(blank=True, default='', max_length=255, verbose_name='实测描述')),
                ('is_qualified', models.BooleanField(default=True, verbose_name='是否合格')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='qms.qualityinspectionitem', verbose_name='检验项目')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='qms.qualityinspectionorder', verbose_name='检验单')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '检验结果',
                'verbose_name_plural': '检验结果',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='版本号')),
                ('issue_no', models.CharField(max_length=32, verbose_name='问题编号')),
                ('title', models.CharField(max_length=255, verbose_name='问题标题')),
                ('category', models.CharField(choices=[('material', '原材料'), ('craft', '工艺'), ('equipment', '设备'), ('design', '设计'), ('operation', '操作'), ('storage', '储运'), ('other', '其他')], db_index=True, default='material', max_length=16, verbose_name='问题分类')),
                ('severity', models.CharField(choices=[('minor', '轻微'), ('major', '严重'), ('critical', '致命')], default='major', max_length=16, verbose_name='严重程度')),
                ('phenomenon', models.TextField(verbose_name='问题现象')),
                ('cause', models.TextField(blank=True, default='', verbose_name='原因分析')),
                ('corrective_action', models.TextField(blank=True, default='', verbose_name='纠正措施')),
                ('preventive_action', models.TextField(blank=True, default='', verbose_name='预防措施')),
                ('product_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='产品 / 物料描述')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='发布时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.material', verbose_name='关联物料')),
                ('source_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qms.qualityalert', verbose_name='来源质量报警')),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qms.qualityinspectionorder', verbose_name='来源检验单')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '质量问题知识库',
                'verbose_name_plural': '质量问题知识库',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='qualityinspectionitem',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_qms_item_company_code'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectionitem',
            constraint=models.CheckConstraint(condition=models.Q(('lower_limit__isnull', True), ('upper_limit__isnull', True), ('lower_limit__lte', models.F('upper_limit')), _connector='OR'), name='ck_qms_item_limit_order'),
        ),
        migrations.AddIndex(
            model_name='qualityinspectionorder',
            index=models.Index(fields=['status', 'judgement'], name='idx_qms_order_state'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectionorder',
            constraint=models.UniqueConstraint(fields=('company', 'order_no'), name='uq_qms_order_company_no'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectionorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='ck_qms_order_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectionorder',
            constraint=models.CheckConstraint(condition=models.Q(('sample_quantity__gte', 0)), name='ck_qms_order_sample_non_negative'),
        ),
        migrations.AddIndex(
            model_name='qualityalert',
            index=models.Index(fields=['status', 'level'], name='idx_qms_alert_state'),
        ),
        migrations.AddConstraint(
            model_name='qualityalert',
            constraint=models.UniqueConstraint(fields=('company', 'alert_no'), name='uq_qms_alert_company_no'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectionresult',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='uq_qms_result_order_item'),
        ),
        migrations.AddConstraint(
            model_name='qualityissue',
            constraint=models.UniqueConstraint(fields=('company', 'issue_no'), name='uq_qms_issue_company_no'),
        ),
    ]
